server:
  port: 8380
spring:
  profiles: # profiles 설정  active에 따라 디폴트 환경을 변경해줄수있다
    active: dev
  spring:
    security:
      debug: true
      oauth2:
        client:
          registration:
            google:
              client-id: google-client-id
              client-secret: google-client-secret
            coocon:
              client-id: client-id
              client-secret: client-secret
              redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
              authorization-grant-type: authorization_code
            kakao:
              client-id: client-id
              client-secret: client-secret
              redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              client-name: Kakao
              scope:
                - profile_nickname
                - profile_image
          provider:
            coocon:
              authorization-uri: http://localhost:8080/oauth/authorize
              token-uri: http://localhost:8080/oauth/token
              user-info-uri: http://localhost:8080/v2/user/me
              user-name-attribute: id
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8180/jwt/issuer
            jwk-set-uri: https://idp.example.com/oauth2/jwks
            public-key-location: classpath:public.pem
logging:
  level:
    com: debug
