server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
    import: application-security-dev.yml
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  application:
    name: admin-local
logging:
  level:
    org.hibernate.type: trace
    com: debug
