spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          coocon:
            client-id: coocon-admin
            client-secret: 1234567890!@
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
          kakao:
            client-id: kakao-client-id
            client-secret: kakao-client-secret
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          coocon:
            authorization-uri: http://localhost:3000/login
            token-uri: http://localhost:8080/oauth/token
            user-info-uri: http://localhost:8080/member/me
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    filter:
      order: -50
