server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
    import: application-security-dev.yml
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
    # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  application:
    name: admin-dev
logging:
  level:
    org.hibernate.type: trace
    com: debug
    org.springframework.security: debug
